--DROP TABLE Zaselenie;
--DROP TABLE preduslug;
--DROP TABLE nomera;
--DROP TABLE personal;
--DROP TABLE dopuslugi;
--DROP TABLE Clienti;
--DROP TRIGGER DateOUT ON Zaselenie;
--DROP TRIGGER DateIN ON Zaselenie;
--DROP TRIGGER ZasCond ON Zaselenie;
--DROP TRIGGER PuslAvail ON Zaselenie;

